FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    g++ \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    torch \
    sentence-transformers>=5.1.2 \
    numpy

COPY models/orig_model.pt /app/model.pt

COPY benchmark.py /app/

CMD ["python", "benchmark.py"]